version: '2'
services:
    ngnx:
        build:
            context: ./
            dockerfile: docker/ngnx/Dockerfile
        volumes:
            - ./buyme-api:/var/www
        ports:
            - "8080:80"
            - "443:443"
            - "9000:9000"
        links:
            - api
    api:
        build:
            context: ./
            dockerfile: docker/api/Dockerfile
        volumes:
            - ./buyme-api:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        image: mysql:5.7.18
        environment:
            - "MYSQL_ROOT_PASSWORD=buyme"
            - "MYSQL_DATABASE=buyme"
            - "MYSQL_USER=buyme"
            - "MYSQL_PASSWORD=buyme"
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/storage:/var/lib/mysql
    client:
        build:
          context: .
          dockerfile: docker/client/Dockerfile
        command: ember server --live-reload-port 35730
        volumes:
          - ./buyme-todo:/usr/src/app
        stdin_open: true
        tty: true
        ports:
          - 4200:4200
          - 35730:35730
        environment:
          SOME_URL: http://localhost:4200